version: "2.3"
services:
  worklist_message_group_tail:
    image: docker.elastic.co/observability/stream:v0.20.0
    hostname: worklist_message_group_tail
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config.yml
